services:
  unit:
    build: .
    restart: unless-stopped
    volumes:
      - ./.unit/config.json:/docker-entrypoint.d/config.json:ro
      # - ./.nginx/ssl/:/etc/ssl/:ro
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    expose:
      - "80"
      - "443"
      - "8080"
