services:
  unit-test-app:
    build: .
    # image: nginx/unit:1.22.0-node15
    # container_name: nginx-unit
    # restart: unless-stopped
    volumes:
      - ./.unit/config-static.json:/docker-entrypoint.d/config.json:ro
      - ./public:/www/public
      - ./src:/www/modules
      - ./www/app.js:/www/app.js
      # - ./.nginx/ssl/:/etc/ssl/:ro
    # volumes:
    #   - type: bind
    #     source: ./www/config.json
    #     target: /docker-entrypoint.d/config.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    expose:
      - "80"
      - "443"
      - "8080"
